<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.0" />
    <PackageReference Include="NuGet.Packaging" Version="7.9.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.9.0" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.11" />
    <PackageReference Include="SourceGear.sqlite3" Version="3.53.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NuGet.TestServer.Extensions.Abstractions\NuGet.TestServer.Extensions.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Vulnerabilities\Embedded\*.json" />
    <InternalsVisibleTo Include="NuGet.TestServer.Cli" />
    <InternalsVisibleTo Include="NuGet.TestServer.FunctionalTests" />
    <InternalsVisibleTo Include="NuGet.TestServer.RouteFixture" />
    <InternalsVisibleTo Include="NuGet.TestServer.UnitTests" />
  </ItemGroup>

</Project>
